DELETE FROM T_USER;
INSERT INTO T_USER(USERNAME,PASSWORD,SEX,AGE,REMARK) VALUES('张三','123456','1',25,'测试数据张三大哥');
INSERT INTO T_USER(USERNAME,PASSWORD,SEX,AGE,REMARK) VALUES('李斯','123456','1',25,'测试数据张三大哥');
INSERT INTO T_USER(USERNAME,PASSWORD,SEX,AGE,REMARK) VALUES('王武','123456','1',25,'测试数据张三大哥');
INSERT INTO T_USER(USERNAME,PASSWORD,SEX,AGE,REMARK) VALUES('刘晓明','123456','1',25,'测试数据张三大哥');
INSERT INTO T_USER(USERNAME,PASSWORD,SEX,AGE,REMARK) VALUES('大帅比','123456','1',25,'测试数据张三大哥');