CREATE TABLE IF NOT EXISTS T_USER(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户名',
  PASSWORD VARCHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
  SEX CHAR(1) NOT NULL DEFAULT '0' COMMENT '性别',
  AGE INT NOT NULL DEFAULT 0 COMMENT '年龄',
  REMARK VARCHAR(100) NOT NULL DEFAULT '' COMMENT '备注'
);

CREATE TABLE IF NOT EXISTS movie(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(32) NOT NULL DEFAULT '' COMMENT '电影名',
  rate VARCHAR(10) NOT NULL DEFAULT '' COMMENT '',
  releaseyear VARCHAR(32) NOT NULL DEFAULT '0' COMMENT '发布年份',
  sendtime VARCHAR(32) NOT NULL DEFAULT 0 COMMENT '',
  daoyan VARCHAR(32) NOT NULL DEFAULT '' COMMENT '导演',
  jianjie VARCHAR(32) NOT NULL DEFAULT '' COMMENT '简介'
);